version: '3.7'

services:
  cinema_db:
    container_name: cinema_db
    restart: unless-stopped
    image: postgres:13
    env_file:
      - ./env/.env
    volumes:
      - /srv/cinema/cinema_posgres:/var/lib/postgresql/data/
      - ./docker/init_db:/docker-entrypoint-initdb.d
    expose:
      - 5432

  cinema_django:
    container_name: cinema_admin_panel
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./infra/docker/cinema_django/Dockerfile
    env_file:
      - ./env/.env
    volumes:
      - ../cinema_django:/cinema_django
      - /srv/cinema/cinema_django/cinema_static:/cinema_django/data/static_backend
      - /srv/cinema/cinema_django/cinema_media:/cinema_django/data/media_backend
    expose:
      - 8000
    depends_on:
      - cinema_db

  cinema_nginx:
    container_name: cinema_nginx
    restart: unless-stopped
    image: nginx:1.19.2
    volumes:
      - /srv/cinema/cinema_django/cinema_static:/cinema_django/data/static_backend
      - /srv/cinema/cinema_django/cinema_media:/cinema_django/data/media_backend
      - ./docker/cinema_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/cinema_nginx/configs:/etc/nginx/conf.d/:ro
    depends_on:
      - cinema_django
    ports:
      - "80:80"

  cinema_es:
    container_name: cinema_fastapi_elastic
    restart: always
    image: elasticsearch:7.17.3
    volumes:
      - /srv/cinema/cinema_es/data:/srv/cinema/cinema_es/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - 9200:9200

  cinema_redis:
    container_name: cinema_fastapi_redis
    restart: always
    image: redis
    volumes:
      - /srv/cinema/cinema_redis/data:/srv/cinema/cinema_redis/data
    depends_on:
      - cinema_es
    ports:
      - 6379:6379

  elt_pg_to_sqlite:
    container_name: elt_pg_to_sqlite
    restart: always
    build:
      context: ..
      dockerfile: ./infra/docker/elt_pg_to_sqlite/Dockerfile
    volumes:
      - ../elt_pg_to_sqlite:/elt_pg_to_sqlite
    env_file:
      - ./env/.env
    depends_on:
      - cinema_django

volumes:
  cinema_posgres:
  cinema_django:
  cinema_static:
  cinema_media:
  cinema_es:
  cinema_redis:
  elt_pg_to_sqlite:
